version: '3.2'
services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=postgres'
    networks:
      - bridge
  redis:
    image: 'redis'
    container_name: 'redis'
    ports:
      - 6379:6379
    networks:
      - bridge
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'employees'
    ports:
      - 8080:8080
    depends_on:
      - redis
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
      - 'SPRING_DATA_REDIS_HOST=redis'
      - 'SPRING_DATA_REDIS_PORT=6379'
    networks:
      - bridge

networks:
  bridge:
    driver: bridge